### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by mhor** [comment]
Sorry I merge previous branch too fast

**Comment by GrahamCampbell** [comment]
They were existing issues with your phpdoc which StyleCI made me notice, so I've sorted them out. :)

**Comment by mhor** [comment]
:smile: thanks

**Comment by GrahamCampbell** [comment]
If you ever have any questions about StyleCI further down the line, feel free to get in touch. :)

**Comment by mhor** [comment]
Ok, @GrahamCampbell :+1:

**Pull request merged**
