### PR TITLE
Update MediaInfoCommandRunner.php

### LINKED ISSUE #106: Process does not work on Windows / wrong ENV-definition
The command syntax on windows is slightly different as on linux/mac os.

linux/mac os: `mediainfo "$MEDIAINFO_VAR_0" "$MEDIAINFO_VAR_1" "$MEDIAINFO_VAR_2"`

windows: `MediaInfo.exe "%MEDIAINFO_VAR_0%" "%MEDIAINFO_VAR_1%" "%MEDIAINFO_VAR_2%"`

### PR DESCRIPTION
**Pull request by cklm**
fixes #106

### CODE REVIEW

**Comment by mhor** [comment]
Hi @cklm thanks for your PR, Symfony Process component |documentation](https://symfony.com/doc/3.4/components/process.html) use this syntax for Windows env var:

```php
// On Windows
$process = new Process('echo "!MESSAGE!"');

// On both Unix-like and Windows
$process->run(null, ['MESSAGE' => 'Something to output']);
```

Could you try with this syntax , and make sure your fix is compatible accross currently supported php-mediainfo, symfony version (https://github.com/mhor/php-mediainfo/blob/master/composer.json#L14) ?

**Comment by cklm** [comment]
Hi @mhor the difference between the percent-sign and the exclamation-mark is described here:
https://stackoverflow.com/questions/14347038/why-are-my-set-commands-resulting-in-nothing-getting-stored/14347131#14347131

Using the percent-signs seems more compatible to me - the exclamation marks must be enabled first with `setlocal EnableDelayedExpansion` which must be added additionally in win-xp (nobody should care about xp, but because ;) ).
Best practice would be to use `$process->run(null, ['MESSAGE' => 'Something to output']);` and give it to symfony-component but that would require more refactoring, since it cannot be set in the constructor.

> Could you try with this syntax , and make sure your fix is compatible accross currently supported php-mediainfo, symfony version

Does not make a difference between php- or symfony-versions, since it is executed directly in shell in windows. Would be a problem, when some windows-version changes that, but of today that works in every windows-version.

**Comment by cklm** [comment]
ping @mhor

**Comment by mhor** [comment]
Thanks you @cklm, Released as [4.1.3](https://github.com/mhor/php-mediainfo/releases/tag/4.1.3)

**Comment by cklm** [comment]
Thank you!

**Pull request merged**
