### PR TITLE
mediainfocontainer-dump-xml

### PR DESCRIPTION
**Pull request by javiertrejo**
Hi @mhor,

I added support to dump MediaInfoContainer or any Type to XML.

Unit Test Added.

Regards,

### CODE REVIEW

**Comment by javiertrejo** [comment]
Hi @mhor, you have time to see this request? 

Regards,

**Comment by mhor** [comment]
Hi @javiertrejo,  could you:
- sync your fork with this repository => https://help.github.com/articles/syncing-a-fork/
- remove test.mp3
- update README with new features
- update pull request title

**Comment by javiertrejo** [comment]
Hi @mhor,

The requested changes has been applied. Sorry for my mistake, i'm a newbie with forking 3rd party projects and contributing.
To dump to YAML it's necesary use PECL/YAML extension. This is not a common part of PHP installations but is possible to do.
Considers useful and necessary to have the option to dump to YAML?
The next week i will be applied this project in a production environment. If any bug will be detected; i will send to you a new pull request with the fixs.

Regards,

**Comment by mhor** [comment]
@javiertrejo I didn't know if dumping to YAML is useful. To dump yaml IMO the easiest way is the use of [YAML symfony component](http://symfony.com/doc/current/components/yaml/introduction.html)

Thanks for pull request I will merge it!

**Comment by mhor** [comment]
@javiertrejo merged and released as [2.1.0](https://github.com/mhor/php-mediainfo/releases/tag/2.1.0)

**Pull request merged**
