### PR TITLE
Symfony 6 components

### LINKED ISSUE #129: Symfony 6 components
Is support for Symfony 6 components planned? Both `symfony/process` and `symfony/filesystem` have a 6.0.0 release now.

Thanks for you work!

### PR DESCRIPTION
**Pull request by TimGels**
The aim of this pull request is to enable Symfony 6 support to resolve #129. Let me know if I missed something : )

### CODE REVIEW

**Comment by mhor** [comment]
Thanks @TimGels could you also update [code_checks.yml](https://github.com/mhor/php-mediainfo/blob/master/.github/workflows/code_checks.yml#L86-L100), to check with last components version

**Comment by TimGels** [comment]
I will take a look in the upcoming days

**Comment by TimGels** [comment]
The Symfony 6 workflow ran without issues on my fork. But there was a warning about setup-php v1 being deprecated.

**Comment by mhor** [comment]
Thanks @TimGels, Merged and released as [5.4.1](https://github.com/mhor/php-mediainfo/releases/tag/5.4.2)

**Comment by mhor** [comment]
FYI @TimGels I've migrated shivammathur/setup-php to v2  (see PR https://github.com/mhor/php-mediainfo/pull/131)

**Comment by TimGels** [comment]
Nice,, that should fix the deprecation warning that was popping up in the CI.

**Pull request merged**
