### PR TITLE
Allow compatibility with symfony4 components

### PR DESCRIPTION
**Pull request by fvilpoix**
Hi,
Here is my contrib to allow to include php-mediainfo into SF4 projects. Fixing #77.

I had to upgrade phpunit version to 5, because of a fatal error with PHP7.

phpunit 5 needs php >= 5.6, so we have to choose between php7 compatibiliy or php >= 5.4 < 7...

Maybe you could merge this commit into a dedicated branch, on which the support of php5 is dropped ?

### CODE REVIEW

**Comment by mhor** [comment]
Thanks for your PR @fvilpoix: 
- I'm ok to drop support of php < 5.6
- Could you try to update travis conf to test this package against different version of symfony deps. I suggest you to test php5.6 with the lowest symfony deps (2.7 and 3.0) and php7.2 with the highest symfony deps (2.8/3.4/4.0)

**Comment by fvilpoix** [comment]
Is it ok for you like this ?

**Comment by mhor** [comment]
LGTM :+1:. Could you just fix StyleCI build ?

**Comment by fvilpoix** [comment]
Ahah, too late :)

**Pull request merged**
