### PR TITLE
Feature/mediainfocontainer dump

### PR DESCRIPTION
**Pull request by javiertrejo**
Added support to dump json and array

```php
$mediaInfo = new MediaInfo();
$mediaInfoContainer = $mediaInfo->getInfo('music.mp3');

$json = json_encode($mediaInfoContainer);
$arr = $mediaInfoContainer->__toArray();
```
Basically, AbstractType and MediaInfoContainer implements [JsonSerializable](http://php.net/manual/en/class.jsonserializable.php).

**IMPORTANT!**
**Requiered PHP 5.4.0**

### CODE REVIEW

**Comment by mhor** [comment]
Hi @javiertrejo, thank you for the pull request, could you:
- remove ``composer.phar``, ``composer.lock` and ``vendor`` directory
- add some unit test

related #34

**Comment by javiertrejo** [comment]
Hi @mhor i removed the vendor dir, and composer.phar and .lock.

I'm not an expert with unit tests but, it's necesary add test for json_encode($mediaInfoContainer) and $mediaInfoContainer->__toArray()? In the worst case, both methods return an empty json object ({}) or an empty array ([]).

But other side, I don't understand why failure travis-ci can you help me with that?

Regards,

**Comment by mhor** [comment]
@javiertrejo thanks for changes. 
For Travis-CI failures:
- 5.3.3 & 5.3: mininum PHP version requirement inconsistency, you can remove checks [here](https://github.com/mhor/php-mediainfo/blob/master/.travis.yml#L6-L7)).
- others version: code style issues (see details [here](https://travis-ci.org/mhor/php-mediainfo/jobs/127071345#L276))

Unit tests are the only way to be sure code works, and unit test can be also used has code documentation

**Comment by javiertrejo** [comment]
Hi @mhor,

I added the unit tests but to run the tests the client must have mediainfo installed or you have a workarround to fill the mediainfocontainer without call mediainfo->getinfo(...).

Regards

**Comment by mhor** [comment]
@javiertrejo you can create a MediaInfoContainer programmatically:

```php
$mediaInfoContainer = new MediaInfoContainer();
$audio = new Audio();
$audio->set('test', 'test');
$mediaInfoContainer->addAudio($audio);
//...
```

**Comment by javiertrejo** [comment]
Hi @mhor

Now the unit tests are ok and passed scrutinizer and travis-ci. But the StyleCI error continue, i don't understand this report https://styleci.io/analyses/qor9pN. What is the course of action? 

Regards

**Comment by mhor** [comment]
Thanks @javiertrejo 
Merged, and released as [2.0.0](https://github.com/mhor/php-mediainfo/releases/tag/2.0.0)

For StyleCI fail I applied this [PR](https://github.com/mhor/php-mediainfo/pull/51)

**Pull request merged**
